version: '3.9'
services:

  mongo: 
    image: mongo 
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: password123 
    ports: 
      "270017": "27017" 
    volumes: 
      -mongodb-data:/data/db 

  tasker: 
    build: . 
    command: ["./tasker"] 
    volumes: 
      - "./data:/app/data" 
    depends_on: 
      - mongodb 

    