version: '3.9'
services:

  mongo: 
    image: mongo 
    restart: always 
    env_file: 
      - ./.env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
    ports: 
      "270017": "27017" 
    volumes: 
      -mongodb-data:/data/db 

  tasker: 
    build: . 
    command: ["./tasker"] 
    volumes: 
      - "./data:/app/data" 
    depends_on: 
      - mongodb 

    